### ISSUE TITLE
Warning: Failed to retrieve NiceHash profitability stats [Errno -3]

### ISSUE THREAD

**Issue by lordmahan** [YoRyan/nuxhash#11]
`WARNING: Failed to retrieve NiceHash profitability stats: [Errno -3] Temporary failure in name resolution`

**Comment by lordmahan** [comment]
I tried to solve it with adding the IP of the api.nicehash.com to `/etc/hosts`
`104.16.83.46    api.nicehash.com        nicehash`
 then sometimes another warning appears:
`WARNING: Failed to retrieve NiceHash profitability stats: timed out`
but now it switches algorithms. is it ok? should i ignore this warning?

**Comment by YoRyan** [comment]
This warning has no adverse effects. If the daemon can't reach NiceHash servers, it prints the cause and leaves the miner alone. It will profit-switch again when the connection comes back online. Meanwhile, excavator will idle GPU.
