### ISSUE TITLE
Package not found?

### ISSUE THREAD

**Issue by snarkyalyx** [YoRyan/nuxhash#116]
After updating oh Arch, I started getting this error - haven't updated in 2 weeks
```
sudo nuxhashd
Traceback (most recent call last):
  File "/usr/bin/nuxhashd", line 33, in <module>
    sys.exit(load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')())
  File "/usr/bin/nuxhashd", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for nuxhash

```

I do have python 3.10 installed.

**Comment by cprn** [comment]
I can only say there's no such issue on Manjaro (which is Arch based so it probably should be present if the package or base distribution were at fault). Did you try to reinstall the package?

**Comment by benthetechguy** [comment]
If you're using my AUR package `nuxhash-git`, you may have to rebuild the package; AUR packages stay on 3.9 until they're updated or rebuilt.
