### ISSUE TITLE
CRITICAL: Crash! Killing all miners

### ISSUE THREAD

**Issue by Poisonsting** [YoRyan/nuxhash#19]
When attempting to run nuxhash for the first time, the following crash occurs:

> Traceback (most recent call last):
  File "/usr/local/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b0', 'console_scripts', 'nuxhashd')()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 106, in main
    nx_miners, nx_settings, all_devices, nx_benchmarks)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/daemon.py", line 146, in run_missing_benchmarks
    miner.load()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 398, in load
    self.server.start()
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/miners/excavator.py", line 125, in start
    raise miner.MinerStartFailed
nuxhash.miners.miner.MinerStartFailed
2018-11-02 23:01:58,584 CRITICAL: Crash! Killing all miners.
Killed

This crash happens on both my desktop (KDE Neon) and my headless server (Ubuntu 18.04)

**Comment by oneEyedCharlie** [comment]
Do you have excavator installed?  And in its normal place?

**Comment by YoRyan** [comment]
Nuxhash automatically downloads excavator to `~/.config/nuxhash/excavator/excavator`. Check that the binary is there and runnable. Do you have Nvidia's CUDA libraries installed?

**Comment by Poisonsting** [comment]
Well, that fixed the error on my Workstation, but not the server. It doesn't appear that your tool supports CPU mining at all?

**Comment by oneEyedCharlie** [comment]
> Well, that fixed the error on my Workstation, but not the server. It doesn't appear that your tool supports CPU mining at all?

What did you do to fix it?

**Comment by Poisonsting** [comment]
Somehow my workstation was missing the CUDA libs.

**Comment by YoRyan** [comment]
That's correct, no CPU mining for now.

**Comment by avelis26** [comment]
What would it take to get CPU mining implemented???
I'm a decent Python scripter but I'm just getting started on learning everything about digital currency so no clue of the complexity but I would certainly love to help if able.

**Comment by submergedbubble** [comment]
do we have a time when we will have cpu mining?
