### ISSUE TITLE
NiceHash platform transition changes

### ISSUE THREAD

**Issue by starlingfire** [YoRyan/nuxhash#28]
NiceHash has announced their transition to a new platform:
https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform

Does this require any changes to the Nuxhash miner? Item #9 mentions changes to their API calls:

> If you are using any API calls, please make sure you update your settings according to [our new API documentation](https://docs-test.nicehash.com/). Buyers, please note that USA hash-power marketplace on the new platform and EU hash-power marketplace on the current platform have a different API!

**Comment by YoRyan** [comment]
As of now, the old API seems to be still in service, but I will investigate updating ASAP.

**Comment by hazemhagrass** [comment]
Same issue here! The Nuxhash app is not working with the new Nicehash platform.
Also for some reason, the Nuxhash app was not profitable at all compared by the Nicehash windows app. Does it make sense?

**Comment by YoRyan** [comment]
Yes. NiceHash has abandoned work on excavator and switched to more profitable third-party miners. I need to write new downloaders and drivers for them.
