### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by pawiromitchel** [YoRyan/nuxhash#29]
Hi,

Nice project btw, but I can't run nuxhashd for some reason. I tried to install the project a couple of times. Any thoughts?

![image](https://user-images.githubusercontent.com/11035568/61172156-1b48bb80-a557-11e9-805a-c572e2cc3426.png)

**Comment by pawiromitchel** [comment]
This issue fixed it for me https://github.com/YoRyan/nuxhash/issues/27, closing issue

**Comment by YoRyan** [comment]
Will reopen until fixed, thanks for reporting.
