### ISSUE TITLE
nuxhash install errors

### ISSUE THREAD

**Issue by dsfcom** [YoRyan/nuxhash#31]
Errors installing when attempting to run the command below; all dependencies have been installed/upgraded. One error appears to be about Python being out of date but when the update is executed the system reports already upgraded. Ubuntu 16.04.5 LTS.

`$ sudo pip3 install git+https://github.com/YoRyan/nuxhash
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/YoRyan/nuxhash
  Cloning https://github.com/YoRyan/nuxhash to /tmp/pip-rlcrxmbq-build
  Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/YoRyan/nuxhash /tmp/pip-rlcrxmbq-build
Cannot find command 'git'
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by avm-xandry** [comment]
sudo apt-get install git?

**Comment by dsfcom** [comment]
I did attempt a "sudo apt intall git" command and it seemed to work but the following was the restult:

`
The directory '/home/dsfcom/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/dsfcom/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/YoRyan/nuxhash
  Cloning https://github.com/YoRyan/nuxhash to /tmp/pip-4kmmd00g-build
Installing collected packages: nuxhash
  Running setup.py install for nuxhash ... done
Successfully installed nuxhash-1.0.0b2
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

**Comment by avm-xandry** [comment]
Well, you can try to update pip with command which you see in the text.

**Comment by dsfcom** [comment]
I tried that as well; the following is the result:

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (19.2.3)`

**Comment by YoRyan** [comment]
> I did attempt a "sudo apt intall git" command and it seemed to work but the following was the restult after another "sudo pip3 intall git+https://github.com/YoRyan/nuxhash":

This is a successful install. The pip cache stuff is just a minor permissions problem (because you ran pip install as root), and you can ignore the warning about the outdated pip version.

New executables should have been installed to `/usr/local/bin`. If you have any problems running the program itself, just let me know.
