### ISSUE TITLE
NiceHash "New Site" Update Has Stopped NuxHash From Showing Account Info

### ISSUE THREAD

**Issue by prometx** [YoRyan/nuxhash#33]
Hi, 

NiceHash have recently migrated to a new system/site. This has required users' new login. While previously mined Sats seem to be correct, the update has forced a NiceHash wallet address change.

I have updated this new "working wallet" in NuxHash settings, NuxHash seems to be mining, but "Daily Revenue" and "Address Balance" are "0.00000000". Will there be a way to assure that NuxHash is still performing as expected with this new NiceHash system?

Thanks!

**Comment by YoRyan** [comment]
Looks like NiceHash locked the account balance behind a non-public endpoint in the new platform (#28). So, in addition to my job - updating Nuxhash to work with the new API - everyone will have to make their own API keys to grant Nuxhash (limited, secure) access to their accounts.

**Comment by prometx** [comment]
Awesome, thanks very much for tracking that down! Your work on NuxHash is very much appreciated. You're tempting me to build a "legit" rig, lol... ;)

**Comment by prometx** [comment]
Hi, any news regarding this?

**Comment by YoRyan** [comment]
Mining with the new API is now working. The balance display will take a little bit more work.

**Comment by YoRyan** [comment]
Fixed with https://github.com/YoRyan/nuxhash/commit/4928c5f6f8d6c3b4751badc501c690f007835dee.

**Comment by prometx** [comment]
Right on, thanks man!
