### ISSUE TITLE
After updating nuxhash doesn't work anymore.

### ISSUE THREAD

**Issue by UbuntuSteve** [YoRyan/nuxhash#35]
Nuxhash has stopped working for me.  Please help
nuxhash-gui
/home/steve/.local/lib/python3.6/site-packages/wx/lib/pubsub/__init__.py:25: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  wx.wxPyDeprecationWarning)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

(nuxhash-gui:5113): Gtk-CRITICAL **: 13:55:33.684: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.684: gtk_widget_size_allocate(): attempt to allocate widget with width 12 and height -12

(nuxhash-gui:5113): Gtk-CRITICAL **: 13:55:33.684: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

(nuxhash-gui:5113): Gtk-CRITICAL **: 13:55:33.687: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.687: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.687: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.687: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.687: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.687: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.687: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.696: Negative content width -15 (allocation 1, extents 8x8) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.708: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5113): Gtk-WARNING **: 13:55:33.708: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 138, in request
    balance = unpaid_balance(address)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 47, in unpaid_balance
    result = api_call('stats.provider', { 'addr': address })
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 34, in api_call
    % urlencode(get_data), timeout=TIMEOUT) as request:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by YoRyan** [comment]
This looks to me like APIv1 getting killed off. Pull for the new APIv2 implementation, and hopefully that will get you mining again.

**Comment by UbuntuSteve** [comment]
What is the exact procedure to "Pull for the new APIv2 implementation" I did the --update earlier to try and fix it before.

Thank you!

**Comment by YoRyan** [comment]
`$ sudo pip3 install git+https://github.com/YoRyan/nuxhash`

**Comment by UbuntuSteve** [comment]
The GUI seems to be running and the button changes to "Stop Mining" but it doesn't seem to be working The "Stop Mining" also does not work
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds

I have to use "Force Quit" to kill it.

Here is the whole terminal below:
nuxhash-gui
/home/steve/.local/lib/python3.6/site-packages/wx/lib/pubsub/__init__.py:25: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  wx.wxPyDeprecationWarning)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(nuxhash-gui:5536): Gtk-CRITICAL **: 14:55:05.002: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.002: gtk_widget_size_allocate(): attempt to allocate widget with width 12 and height -12

(nuxhash-gui:5536): Gtk-CRITICAL **: 14:55:05.002: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(nuxhash-gui:5536): Gtk-CRITICAL **: 14:55:05.004: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.004: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.004: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.004: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.004: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.004: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.004: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.011: Negative content width -15 (allocation 1, extents 8x8) while allocating gadget (node entry, owner GtkEntry)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.020: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(nuxhash-gui:5536): Gtk-WARNING **: 14:55:05.020: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/gui/mining.py", line 138, in request
    balance = unpaid_balance(address)
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 47, in unpaid_balance
    result = api_call('stats.provider', { 'addr': address })
  File "/usr/local/lib/python3.6/dist-packages/nuxhash/nicehash.py", line 34, in api_call
    % urlencode(get_data), timeout=TIMEOUT) as request:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
WARNING:root:NiceHash stats: The read operation timed out, retrying in 5 seconds
Killed

**Comment by YoRyan** [comment]
Apologies, it looks like that command didn't actually update you. Try bypassing the cache with `$ sudo pip3 install git+https://github.com/YoRyan/nuxhash --no-cache-dir`.

**Comment by UbuntuSteve** [comment]
Sorry but that again did not help

sudo pip3 install git+https://github.com/YoRyan/nuxhash --no-cache-dir
[sudo] password for steve: 
Collecting git+https://github.com/YoRyan/nuxhash
  Cloning https://github.com/YoRyan/nuxhash to /tmp/pip-hourdiio-build
  Requirement already satisfied (use --upgrade to upgrade): nuxhash==1.0.0b2 from git+https://github.com/YoRyan/nuxhash in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from nuxhash==1.0.0b2)

Same stuff as before and I had to Force Quit

**Comment by UbuntuSteve** [comment]
I ran it again adding --upgrade at the end and it seems to be working now.  Thank you!!!
