### ISSUE TITLE
Won't Benchmark

### ISSUE THREAD

**Issue by kinteseay** [YoRyan/nuxhash#37]
I'm actually trying to run this in Arch Linux.  When I try to execute the program, either the gui or cli, I can't benchmark.  It just freezes and when I exit, I see where there is a socket timeout.  Is there anything else I need to set up?  In my settings.conf, there is a section on excavator that is blank.  I'm not sure what to do with that.  Also, I set up an api key on nicehash website, but am not sure what to do with it here.  When I run nuxhashd --list-devices, my 2 GPUs show up, so it is detecting them.
[error.txt](https://github.com/YoRyan/nuxhash/files/3703044/error.txt)

**Comment by kinteseay** [comment]
Just an update, After rebooting my computer, I was able to get the benchmarks working.  However, it still won't mine.  When using the gui, I get this error.  Again, I'm wondering if there's something I need to configure in my settings.conf or incorporating my api keys.  Error message is attached
[error2.txt](https://github.com/YoRyan/nuxhash/files/3713647/error2.txt)

**Comment by YoRyan** [comment]
Same error as #35. Probably APIv1.
