### ISSUE TITLE
Current rig profitability goes near/to  0

### ISSUE THREAD

**Issue by JarnDev** [YoRyan/nuxhash#41]
![image](https://user-images.githubusercontent.com/20113585/67152950-d8655500-f2b6-11e9-9ad5-19989b3e4ae2.png)

As you see, I have 3 rigs with GTX1060-6gb, and from time to time they go near/to 0 profitability.

Is this normal? How can I check if my rig is really mining, and not halting from time to time?

**Comment by YoRyan** [comment]
Your mining speed may be constant and predictable, but you only get paid when you find valid hashes, which is a probabilistic process. In the long run, your projected and actual incomes should converge.
