### ISSUE TITLE
Having error downloading

### ISSUE THREAD

**Issue by KillerPriest86** [YoRyan/nuxhash#44]
sudo pip3 install git+https://github.com/YoRyan/nuxhash
The directory '/home/jason/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jason/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

**Comment by YoRyan** [comment]
So sorry for the delay. Permissions are in an inconsistent state. Please follow the error messages.
