### ISSUE TITLE
Settings.conf is missing ubuntu 20

### ISSUE THREAD

**Issue by chabgood** [YoRyan/nuxhash#81]
When I installed nuxhash the settings.conf file is missing.

**Comment by yanrs17** [comment]
I still have it. Maybe you can try to reinstall it?

**Comment by chabgood** [comment]
I reinstalled it, the setting.conf is  not it:

`cd .config/nuxhash/
chabgood@moo:~/.config/nuxhash$ ls -al
total 12
drwxrwxr-x  3 chabgood chabgood 4096 Feb 23 13:48 .
drwxr-x--- 20 chabgood chabgood 4096 Mar  1 21:46 ..
drwxrwxr-x  2 chabgood chabgood 4096 Feb 23 13:48 excavator`

**Comment by chabgood** [comment]
Oh you have to start the gui in order for the settings.conf to show up.

**Comment by Nixellion** [comment]
I would not mark it as closed, and would like to reopen this as an issue, as it IS an issue for headless systems. I don't need GUI for mining, it's something that you set and forget.
